name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - main
      - test-branch # 如果需要在测试环境触发

env:
  APP_JAR: build/libs/*.jar

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    # 1. 选择环境
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'test' }}

    steps:
      # 1. 检出代码
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. 设置 Java 环境
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17

      # 3. 缓存 Gradle 构建依赖
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. 构建项目
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 5. 部署到环境
      - name: Deploy to EC2 using rsync
        env:
          HOST: ${{ github.ref == 'refs/heads/main' && secrets.PROD_EC2_HOST || secrets.TEST_EC2_HOST }}
          USER: ${{ github.ref == 'refs/heads/main' && secrets.PROD_EC2_USER || secrets.TEST_EC2_USER }}
          KEY: ${{ github.ref == 'refs/heads/main' && secrets.PROD_EC2_PRIVATE_KEY || secrets.TEST_EC2_PRIVATE_KEY }}
        run: |
          echo "$KEY" > key.pem
          chmod 600 key.pem
          rsync -e "ssh -i key.pem -o StrictHostKeyChecking=no" -avz ${{ env.APP_JAR }} $USER@$HOST:/home/ec2-user/springboot-app.jar
          rm -f key.pem

      # 6. 启动应用
      - name: Start Spring Boot App on EC2
        env:
          HOST: ${{ github.ref == 'refs/heads/main' && secrets.PROD_EC2_HOST || secrets.TEST_EC2_HOST }}
          USER: ${{ github.ref == 'refs/heads/main' && secrets.PROD_EC2_USER || secrets.TEST_EC2_USER }}
          KEY: ${{ github.ref == 'refs/heads/main' && secrets.PROD_EC2_PRIVATE_KEY || secrets.TEST_EC2_PRIVATE_KEY }}
        run: |
          echo "$KEY" > key.pem
          chmod 600 key.pem
          ssh -i key.pem -o StrictHostKeyChecking=no $USER@$HOST << EOF
            pkill -f 'java -jar' || true
            nohup java -jar /home/ec2-user/springboot-app.jar > /etc/applog/app.log 2>&1 &
          EOF
          rm -f key.pem